### ISSUE TITLE
微信小程序

### ISSUE THREAD

**Issue by SunHengX** [Moonofweisheng/wot-starter#1]
![image](https://github.com/Moonofweisheng/wot-starter/assets/63703285/723f4500-6d66-4f0a-832c-f977bdad1fba)
无法运行的微信小程序上

**Comment by Moonofweisheng** [comment]
![image](https://github.com/Moonofweisheng/wot-starter/assets/26426873/be1bec7c-7a39-4546-a01d-f6b182f74a23)
需要勾选一下这个

**Comment by SunHengX** [comment]
> ![图像](https://user-images.githubusercontent.com/26426873/270898069-be1bec7c-7a39-4546-a01d-f6b182f74a23.png) 需要勾选一下这个

嗯，解决了，没想到回复这么快

**Comment by Moonofweisheng** [comment]
> > ![图像](https://user-images.githubusercontent.com/26426873/270898069-be1bec7c-7a39-4546-a01d-f6b182f74a23.png) 需要勾选一下这个
> 
> 嗯，解决了，没想到回复这么快

看到邮件，我有空的时候就会回复的
