### ISSUE TITLE
启动项目报错

### ISSUE THREAD

**Issue by snowords** [Moonofweisheng/wot-starter#3]
---
> 环境
- node v20.7.0
- npm v10.1.0
---
> 操作步骤
1. ```pnpm i```
2. ```pnpm dev:h5```
---
> 现象
- 控制台报错
- 页面空白
---
![image](https://github.com/Moonofweisheng/wot-starter/assets/22708432/83a71c78-601c-4565-bf68-bb24ad21cd18)

**Comment by Moonofweisheng** [comment]
推测是你使用pnpm安装，而项目内没有pnpm-lock.yaml，导致安装的pinia的版本不对，建议使用yarn安装因为项目里面有yarn.lock。或者你将yarn.lock转成pnpm-lock.yaml，
`pnpm import pnpm-lock.yaml`
