### ISSUE TITLE
怎么修改主题色

### ISSUE THREAD

**Issue by wangruiStart** [Moonofweisheng/wot-starter#5]
在 uni.scss 文件中修改$-color-theme变量没有生效

**Comment by Moonofweisheng** [comment]
今天晚点我在本项目中给个示例

**Comment by wangruiStart** [comment]
我发现好像是修改成功了，checkbox 这类组件的主题是我设置的颜色，但是 button type 为 primary 始终是蓝色

**Comment by Moonofweisheng** [comment]
> 我发现好像是修改成功了，checkbox 这类组件的主题是我设置的颜色，但是 button type 为 primary 始终是蓝色

因为button、tag等组件的主色使用了渐变，并不是直接使用的theme-color，所以无法靠只修改$-color-theme实现自定义。目前阶段建议使用css变量进行覆盖，后面我会优化这个逻辑的
